### ISSUE TITLE
Look for a closer

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/knowledge#18]
I am very good at starting projects. However, the long tail at the end is harder. Recently, while discussing this with some people in the altMBA programme, they brought up the idea of finding a closer to help me out with my projects. Find someone who is consistently good at shipping products and making sure they are wrapped up and finite, instead of dragging them out and continually doing them. 

I don't have a great way to look for this person; I can post on social media about it, or on Hacker Paradise and my other alumni networks. However, I think this is more of a long term goal of mine. Opening this issue to remind myself to be on the lookout for someone who I can organically start working with. 

To Do: Close this issue in three months if there's been no change in status.

**Comment by noffle** [comment]
I send empathy: closing is *hard*. Hope you find someone to complement your style Richard!

**Comment by RichardLitt** [comment]
I am non-ironically closing this, as a practice of closing things.
