### ISSUE TITLE
Translation/Localization

### ISSUE THREAD

**Issue by vinzruzell** [RichardLitt/knowledge#19]
Hi! I would like to request for a Filipino Translation Contribution thru github.

**Comment by RichardLitt** [comment]
Thanks @vinzruzell. Why do you think that this would help?

**Comment by vinzruzell** [comment]
I think this will help for multi language purpose sir. :)

**Comment by RichardLitt** [comment]
Thanks @vinzruzell. As this is a personal repository, and as I don't speak Filipino, I think that this would probably just add overhead for me. If you know of someone who wants to read of any of this, please send them a copy and translate it. It is highly likely someone else has written something better elsewhere, as it is.
