### ISSUE TITLE
Use `git clone user/repo` with enterprise

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/knowledge#5]
How do you do this:

```
git clone user/repo
```

And emulate this:

```
git clone git@github.corp.org:user/repo.git
```

**Comment by noffle** [comment]
[`hub`](https://github.com/github/hub) can do that syntax: `hub clone noffle/foobar`. They recommend you alias `git` to their command, but I prefer to only use `hub` explicitly for `hub`-related behaviours.

**Comment by RichardLitt** [comment]
Unfortunately, it defaults to https AFAIK. Not sure how to make it default to ssh. hub.protocol doesn't seem to work.

**Comment by RichardLitt** [comment]
Also, they don't change the url.

**Comment by RichardLitt** [comment]
@noffle Why do you use hub and not alias?

**Comment by noffle** [comment]
I misunderstood your intention. Is the situation that you have a private corp git server and you want to clone from it, but just use `user/repo` syntax? If so, you should be able to use a small shell script to rewrite `user/repo`. Here's my take:

```
$ cat > clone.sh
#!/usr/bin/env bash

# pull out the words before and after the '/' character
USER=$(echo $1 | sed 's/^\(.*\)\/.*$/\1/g')
REPO=$(echo $1 | sed 's/^.*\/\(.*\)$/\1/g')

# remove the "echo" and quotes to have it run instead of print
echo "git clone git@github.corp.org:${USER}/${REPO}.git"
^D
```

```
./clone RichardLitt/secrets
git clone git@github.corp.org:RichardLitt/secrets.git
```

**Comment by noffle** [comment]
> Why do you use hub and not alias?

Predictability. I know what `hub clone` does, and I know what `git clone` does. If I want the behaviour of `git clone` I'd rather not pass that command through a proxy that might have a different interpretation of what I want it to do.

**Comment by RichardLitt** [comment]
Fascinating! That's a smart idea - I wouldn't have thought of a small script for that. Makes sense. You're fast at `sed`. 

That seems to do the trick, and saves me tons of annoying legwork trying to get config working. Thank you, @noffle. 

What do you do about the hub functions which extend other functions? Just use them through hub? Interesting.

**Comment by RichardLitt** [comment]
As issue is solved, will be closing this. As well, will be continuing my experiment of uploading questions I have here. Seems to be a useful way to log my seeking of knowledge! And thank you, @noffle, for being so kind.

**Comment by noffle** [comment]
> What do you do about the hub functions which extend other functions? Just use them through hub?

I only use `hub clone|fork|pr`, so maybe that's why it hasn't been any trouble for me.

**Comment by noffle** [comment]
Yeah, I like the idea of using one's knowledge repo for longer-form questions like this, where Twitter maybe wouldn't be as convenient.
