### ISSUE TITLE
.gitconfig vs .config/git

### ISSUE THREAD

**Issue by RichardLitt** [RichardLitt/knowledge#6]
Someone told me that `.gitconfig` is now deprecated in favor of `.config/git/config`. However, I can't find any record of this. In terms of the config hierarchy, git looks at them in this order: `/etc/gitconfig`, `~/.gitconfig`, and `~/.config/git/config`. So, moving my entire local `~/.gitconfig` doesn't seem to be a smart idea, as any recreated version by accident will override it if I move it to `~/.config`. Git itself suggests [either place](https://git-scm.com/book/en/v2/Getting-Started-First-Time-Git-Setup).  

Why would I use one, over the other? Is there any benefit?

**Comment by yae2** [comment]
``.config`` is an XDG user directory standard, like ``.cache``, I think. You can change which directory is the ".config" directory with $XDG_CONFIG_HOME. Here's a link or two:

- https://wiki.archlinux.org/index.php/XDG_user_directories
- https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by RichardLitt** [comment]
Interesting! Thanks @yae2. It looks like XDG is just a cross-platform standard, which is useful. On my Mac itself, though, I don't think I'll need to do this, as I don't interact with other UNIX architectures and optimizing to solve that need isn't something I need to do. 

Thank you!
